# Generated by Django 5.0.6 on 2024-11-08 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Room',
            fields=[
                ('room_id', models.UUIDField(primary_key=True, serialize=False)),
                ('room_passwod', models.TextField()),
                ('room_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
