# Generated by Django 5.0.6 on 2024-11-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_room_room_password_uuid_alter_user_room_room_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_room',
            name='room_password_uuid',
        ),
        migrations.AlterField(
            model_name='user_room',
            name='room_id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
