# Generated by Django 5.0.6 on 2024-11-08 19:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_user_room_room_password_uuid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_room',
            old_name='room_passwod',
            new_name='room_last_passwod',
        ),
        migrations.AddField(
            model_name='user_room',
            name='room_password',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_room',
            name='room_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
