# Generated by Django 5.0.6 on 2024-11-08 19:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_room_passwod_user_room_room_last_passwod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_room',
            name='room_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
