# Generated by Django 5.0.6 on 2024-11-08 19:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_user_room_room_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_room',
            old_name='room_last_passwod',
            new_name='room_passwod',
        ),
        migrations.RemoveField(
            model_name='user_room',
            name='room_password',
        ),
        migrations.AlterField(
            model_name='user_room',
            name='room_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
