# Generated by Django 5.0.6 on 2024-11-08 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_user_room_room_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_room',
            old_name='room_passwod',
            new_name='room_password',
        ),
    ]
